orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
version: 2.1
workflows:
  test:
    jobs:
      build:
        docker:
          - image: circleci/node:lts
        steps:
          - checkout
          - run: |
              ls
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          context: myContext
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ./back/
          profile-name: default
          region: AWS_REGION_ENV_VAR_NAME
          repo: ecr-short-url
          skip-when-tags-exist: false
          tag: ${CIRCLE_BRANCH}
